billing/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()

router.register('hsn', views.HSNViewSet)
router.register('bill_products', views.BillingViewSet)

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('', include(router.urls)),
    path('purchases', views.purchases, name='purchases'),
    path('purchases/new', views.purchase_create, name='purchase_create'),

    path('invoices/new', views.invoice_create, name='invoice_create'),
    path('invoices/delete', views.invoice_delete, name='invoice_delete'),
    path('invoices/invoice_viewer/<int:invoice_id>', views.invoice_viewer, name='invoice_viewer'),

    path('login', views.login_view, name='login_view'),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'order/', views.orders),
    path('invoices', views.invoices, name='invoices'),

    path('products', views.products, name='products'),
    path('products/add', views.product_add, name='product_add'),
    path('products/edit/<int:product_id>', views.product_edit, name='product_edit'),
    path('invoices/<int:invoice_id>', views.show_invoice, name='show_invoice'),
    path('get/<int:invoice_id>', views.get_bill, name='get_bill'),
    path('products/delete', views.product_delete, name='product_delete'),

]

home/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .apiviewsets import *


router = DefaultRouter()
router.register(r'category', CategoryViewSet)
router.register(r'products', ProductViewSet)
router.register(r'cart_items', CartItemViewSets)
router.register(r'cart', CartViewSets)
router.register(r'order', OrderViewSets)
router.register(r'address', AddressViewSets)
router.register(r'recipe_box', RecipeBoxViewSet)
router.register(r"reviews", ReviewViewSet)

urlpatterns = [
    path(r'', include(router.urls)),
    path(r'transaction/', confirm_order),
    path(r'payment/', payment),
    path(r'is_available_pincode/', available_pin_codes),
    path(r'get_coupon/', get_coupon),
    ]

prototype/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, authentication
import os
...

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",

        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="sahilathrij@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    authentication_classes=(authentication.SessionAuthentication,),

)


urlpatterns = [

    path('api/', include('home.urls')),
    path('auth/', include('authentication.urls')),
    path('bill/', include('billing.urls')),
    path('', include('auth_login.urls')),
    path('openid/', include('oidc_provider.urls', namespace='oidc_provider')),
    re_path(r'swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path(r'swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path(r'redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path(os.environ.get('ADMIN_URL') + 'log_viewer/', include('log_viewer.urls')),
    path(os.environ.get('ADMIN_URL'), admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_framework_social_oauth2/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from oauth2_provider.views import AuthorizationView

from .views import ConvertTokenView, TokenView, RevokeTokenView, invalidate_sessions

urlpatterns = [
    url(r'^authorize/?$', AuthorizationView.as_view(), name="authorize"),
    url(r'^token/?$', TokenView.as_view(), name="token"),
    url('', include('social_django.urls', namespace="social")),
    url(r'^convert-token/?$', ConvertTokenView.as_view(), name="convert_token"),
    url(r'^revoke-token/?$', RevokeTokenView.as_view(), name="revoke_token"),
    url(r'^invalidate-sessions/?$', invalidate_sessions, name="invalidate_sessions")
]

billing/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from organisation.models import Organisation


class HsnCode(models.Model):
    code = models.CharField(max_length=10, primary_key=True)
    description = models.TextField(max_length=1500, blank=True, null=True)
    gst_percent = models.FloatField(validators=[MaxValueValidator(100), MinValueValidator(0)], blank=True, null=True)

    def __str__(self):
        return self.code


class BillingProduct(models.Model):
    title = models.CharField(max_length=255)
    product_hsn = models.ForeignKey(HsnCode, on_delete=models.SET_NULL, blank=True, null=True)
    product = models.ForeignKey("home.Product", on_delete=models.PROTECT, blank=True, null=True, related_name='sellers')
    code = models.CharField(max_length=8)
    price = models.FloatField()
    stock = models.IntegerField(default=0)
    discount = models.PositiveIntegerField(validators=[MaxValueValidator(100)], default=0)
    price2 = models.FloatField(default=0)
    price3 = models.FloatField(default=0)
    gst_percent = models.PositiveIntegerField(validators=[MaxValueValidator(100)], default=0)
    organisation = models.ForeignKey(Organisation, on_delete=models.PROTECT, blank=True, null=True)
    can_be_cleaned = models.BooleanField(default=False)
    cleaned_price = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.title

billing/forms.py
from django.forms import ModelForm

from billing.models import BillingProduct


class ProductForm(ModelForm):
    class Meta:
        model = BillingProduct
        fields = ['title', 'code', 'price', 'price2', 'price3', 'stock', 'discount', 'gst_percent', 'product_hsn']

    def get_hsn(self):
        return self.instance.product_hsn

billing/views.py
import datetime
import json

import django_filters
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from rest_framework import viewsets, permissions, filters
from rest_framework.decorators import api_view
from rest_framework.response import Response

from authentication.permissions import IsOrganiserUser
from home.models import Orders, OrderItem, Purchase
from home.serializers import OrderSerializer
from .forms import ProductForm
from .models import HsnCode, BillingProduct
from .serializers import HSNSerializer, BillingProductSerializer
from .utils import invoice_data_processor, product_data_processor, create_bill


def test(user):
    return True if user.tokens.organisation else False


def login_view(request):
    if request.user.is_authenticated:
        return redirect("invoice_create")
    context = {}
    auth_form = AuthenticationForm(request)
    if request.method == "POST":
        auth_form = AuthenticationForm(request, data=request.POST)
        if auth_form.is_valid():
            user = auth_form.get_user()
            if user:
                login(request, user)
                return redirect("invoice_create")
        else:
            context["error_message"] = auth_form.get_invalid_login_error()
    context["auth_form"] = auth_form
    return render(request, 'gstbillingapp/login.html', context)


def refactor(request, function, model, org):
    context = {}
    last_order = model.objects.all().order_by('-id').first()
    if last_order:
        context['default_invoice_number'] = last_order.id + 1
    else:
        context['default_invoice_number'] = 1

    context['default_invoice_date'] = datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d')
    if request.method == 'POST':
        invoice_data = json.loads(request.body)

        function(invoice_data, org)

    return context


@login_required
@user_passes_test(test, redirect_field_name='/')
def invoice_create(request):
    context = refactor(request, invoice_data_processor, Orders, request.user.tokens.organisation)

    return render(request, 'gstbillingapp/invoice_create.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def purchase_create(request):
    context = refactor(request, product_data_processor, Purchase, request.user.tokens.organisation)
    return render(request, 'gstbillingapp/purchase_create.html', context)


@api_view(["POST"])
def orders(request):
    invoice_data = request.data

    order = invoice_data_processor(invoice_data, request.user.tokens.organisation)

    serializer = OrderSerializer(data=order, many=False)
    serializer.is_valid(raise_exception=True)
    return Response(serializer.data, status=200)


@login_required
@user_passes_test(test, redirect_field_name='/')
def invoices(request):
    context = {'orders': Orders.objects.filter(organisation=request.user.tokens.organisation).order_by('-id')}
    return render(request, 'gstbillingapp/invoices.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def purchases(request):
    context = {'orders': Purchase.objects.filter(organisation=request.user.tokens.organisation).order_by('-id')}
    return render(request, 'gstbillingapp/purchases.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def invoice_delete(request):
    if request.method == "POST":
        invoice_id = request.POST["invoice_id"]
        invoice_obj = get_object_or_404(Orders, organisation=request.user.tokens.organisation, id=invoice_id)
        invoice_obj.delete()
    return redirect('invoices')


@login_required
@user_passes_test(test, redirect_field_name='/')
def customers(request):
    context = {'customers': User.objects.all()}
    return render(request, 'gstbillingapp/customers.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def products(request):
    context = {'products': BillingProduct.objects.filter(organisation=request.user.tokens.organisation)}
    return render(request, 'gstbillingapp/products.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def product_edit(request, product_id):
    product_obj = get_object_or_404(BillingProduct, id=product_id, organisation=request.user.tokens.organisation)

    if request.method == "POST":
        product_form = ProductForm(request.POST, instance=product_obj)
        if product_form.is_valid():
            product_form.save()
            return redirect('products')
    context = {'product_form': ProductForm(instance=product_obj)}
    return render(request, 'gstbillingapp/product_edit.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def invoice_viewer(request, invoice_id):
    invoice_obj = get_object_or_404(Orders, id=invoice_id, organisation=request.user.tokens.organisation)

    return Response(invoice_obj)


@login_required
@user_passes_test(test, redirect_field_name='/')
def get_bill(request, invoice_id):
    invoice = get_object_or_404(Orders, id=invoice_id, organisation=request.user.tokens.organisation)
    items = OrderItem.objects.filter(order=invoice)

    prefix = invoice.organisation.c_invoice_prefix if invoice.type == "c" else invoice.organisation.b_invoice_prefix

    bill = create_bill(invoice, items, f'{prefix}{invoice.invoice_number}')

    return JsonResponse({"bill": bill})


@login_required
@user_passes_test(test, redirect_field_name='/')
def show_invoice(request, invoice_id):
    invoice = get_object_or_404(Orders, id=invoice_id, organisation=request.user.tokens.organisation)
    items = OrderItem.objects.filter(order=invoice)

    prefix = invoice.organisation.c_invoice_prefix if invoice.type == "c" else invoice.organisation.b_invoice_prefix

    bill = create_bill(invoice, items, f'{prefix}{invoice.invoice_number}')

    context = {"invoice": invoice, "items": items, "invoice_number": f'{prefix}{invoice.invoice_number}', "bill": bill}

    return render(request, 'gstbillingapp/invoice_show.html', context=context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def product_add(request):
    if request.method == "POST":
        product_form = ProductForm(request.POST)

        if product_form.is_valid():
            new_product = product_form.save(commit=False)
            new_product.organisation = request.user.tokens.organisation
            if new_product.product_hsn:
                new_product.product_hsn.gst_percent = new_product.gst_percent
                new_product.product_hsn.save()
            new_product.save()

        print(product_form.errors, product_form.is_valid())

    context = {'product_form': ProductForm()}
    return render(request, 'gstbillingapp/product_edit.html', context)


@login_required
@user_passes_test(test, redirect_field_name='/')
def product_delete(request):
    if request.method == "POST":
        product_id = request.POST["product_id"]
        product_obj = get_object_or_404(BillingProduct, organisation=request.user.tokens.organisation, id=product_id)
        product_obj.delete()
    return redirect('products')


@login_required
@user_passes_test(test, redirect_field_name='/')
def landing_page(request):
    if request.user.tokens.organisation:
        context = {"org": request.user.tokens.organisation}
        return render(request, 'gstbillingapp/pages/landing_page.html', context)
    return redirect('/')


class HSNViewSet(viewsets.ModelViewSet):
    http_method_names = ['get', 'post', 'options']
    queryset = HsnCode.objects.all()
    serializer_class = HSNSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [filters.SearchFilter]
    search_fields = ['code', 'description', ]


class BillingViewSet(viewsets.ModelViewSet):
    http_method_names = ['get', 'post', 'options']
    queryset = BillingProduct.objects.all()
    serializer_class = BillingProductSerializer
    permission_classes = [IsOrganiserUser]
    filter_backends = [filters.SearchFilter, django_filters.rest_framework.DjangoFilterBackend]
    search_fields = ['title', 'code']
    filterset_fields = ['title', 'product_hsn', 'code']

    def get_queryset(self):
        if self.request.user.tokens.organisation:
            return BillingProduct.objects.filter(organisation=self.request.user.tokens.organisation)
        return BillingProduct.objects.none()

billing/templates/gstbillingapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>
		{% block title %}
		GST Billing
		{% endblock %}
	</title>

	{% block metatags %}
	{% endblock %}



	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static "gstbillingapp/bootstrap-4.4.1-dist/css/bootstrap-cosmo.min.css" %}">
	<link rel="stylesheet" href="{% static "gstbillingapp/main.css" %}">


	{% block includecss %}
	{% endblock %}

</head>

<body>

	<div class="container">
		<!-- Content here -->

		{% include "gstbillingapp/navbar.html" %}

		{% if error_message %}
		<div class="alert alert-danger" role="alert">
			{{error_message}}
		</div>
		{% endif %}

		{% if success_message %}
		<div class="alert alert-success" role="alert">
			{{success_message}}
		</div>
		{% endif %}

		{% block content %}
		CONTENT BLOCK
		{% endblock %}

	</div>


	{% block includejs %}
	{% endblock %}



<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-159304253-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-159304253-1');
</script>



</body>


</html>

billing/templates/gstbillingapp/customers.html
{% extends "gstbillingapp/base.html" %}

{% load static %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>Customers</h2>
        </div>
        <div class="col">
            <a href="{% url 'customer_add' %}" id="add_customer_btn">
                <button type="button" class="btn btn-primary">Add New</button>
            </a>
        </div>
    </div>

    <table class="table table-bordered" id="customer-table">
        <thead>
        <tr>
            <th>Customer Name</th>
            <th>email</th>
            <th>Phone</th>
            <th>GST NO</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody class="two-col-form">
        {% for customer in customers %}
            <tr>
                {% if customers.fist_name %}
                    <td>{{ customer.first_name }}</td>
                {% else %}
                    <td>{{ customer.username }}</td>

                {% endif %}

                <td>{{ customer.email }}</td>
                <td>{{ customer.email }}</td>
                <td>{{ customer.email }}</td>
                <td><a href="{% url 'customer_edit' customer.id %}">
                    <button type="button" class="btn btn-dark">Edit</button>
                </a></td>
                <td>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#customerDeleteModal"
                            data-customer-id="{{ customer.id }}" data-customer-name="{{ customer.customer_name }}">
                        Delete
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="modal fade" id="customerDeleteModal" tabindex="-1" role="dialog"
         aria-labelledby="customerDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="customerDeleteModalLabel">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="POST" action="{% url 'customer_delete' %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        Are you sure you want to delete <b><span class="customer-name"></span></b>?
                        <div class="form-group">
                            <input hidden="true" type="text" class="form-control" name="customer_id">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}


{% block includejs %}
    <script type="text/javascript">
        $('#customerDeleteModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var customer_id = button.data('customer-id') // Extract info from data-* attributes
            var customer_name = button.data('customer-name') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            modal.find('.modal-body input').val(customer_id)
            console.log(customer_name)
            modal.find('.customer-name').html(customer_name)
        });


        $(document).ready(function () {
            $('#customer-table').DataTable({
                "order": [],
                "columnDefs": [{
                    "targets": 4,
                    "sortable": false,
                    "searchable": false
                },
                    {
                        "targets": 5,
                        "sortable": false,
                        "searchable": false
                    }],
                "paging": true
            });
        });

    </script>
{% endblock %}

billing/templates/gstbillingapp/invoice_create.html
{% extends "gstbillingapp/base.html" %}

{% load static %}
{% block content %}

    <h2>Create Invoice</h2>

    <form method="POST" id="invoice-form">

        <table class="table table-bordered">
            <thead>
            <tr>
                <th class="table-active" scope="col" colspan="4">Invoice Details</th>
            </tr>
            </thead>

            <tbody class="two-col-form">
            <tr>
                <th scope="row"><label for="invoice_type">Type</label></th>
                <td class="form-input-td">
                    <select id="invoice_type" required>
                        <option value="b">B to B</option>
                        <option value="c" selected>B to C</option>
                    </select>
                </td>
                <th scope="row">Date</th>
                <td class="form-input-td">
                    <input name="invoice-date" type="date" class="form-control" value="{{ default_invoice_date }}"
                           readonly>
                </td>
            </tr>
            </tbody>
        </table>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th class="table-active" scope="col" colspan="7">Customer Details</th>
            </tr>
            </thead>

            <tbody>
            <tr>
                <th scope="row">Customer Name</th>
                <td class="form-input-td customer_search_area">
                    <input autocomplete="off" type="text" class="form-control customer_search_input"
                           list="user_name_options" id="customer-name-input" placeholder="Customer Name" required>
                </td>
                <th scope="row">Customer Address</th>
                <td class="form-input-td" colspan="3">
                    <input type="text" class="form-control" id="customer-address-input" placeholder="Customer Address"
                           required>
                </td>
            </tr>
            <tr>
                <th scope="row">Customer Mobile Number</th>
                <td class="form-input-td">
                    <input type="tel" class="form-control" id="customer-phone-input"
                           list="user_phone_options" placeholder="Customer Mobile Number" required>
                </td>
                <th scope="row">Pin Code</th>
                <td class="form-input-td">
                    <input type="number" class="form-control" id="customer-pin-input" placeholder="PIN Code" required>
                </td>
                <th scope="row">GST</th>
                <td class="form-input-td">
                    <input type="text" class="form-control" id="customer-gst-input" placeholder="Customer GST">
                </td>
            </tr>

            </tbody>
        </table>

        <table class="table table-bordered" id="invoice-form-items-table">
            <thead>
            <tr>
                <th class="table-active" scope="col" colspan="11">Items</th>
            </tr>
            <tr>
                <th scope="col">SlNo</th>
                <th scope="col">Code</th>
                <th scope="col" colspan="4">Product</th>
                <th scope="col">Weight / Qty</th>

                <th scope="col">Price</th>
                <th scope="col">GST %</th>
                <th scope="col">Net Price</th>
            </tr>
            </thead>
            <tbody id="invoice-form-items-table-body">

            </tbody>

            <tr>
                <td colspan="9" class="text-center align-content-center"><strong>TOTAL:</strong></td>
                <td colspan="2" class="text-center">
                    <input id="invoice-total" type="number" step="any" class="form-control" readonly>
                </td>
            </tr>

        </table>
        <td class="form-input-td ">
            <select id="form-category" hidden required>
                <option value="c" selected>invoice</option>
            </select>
        </td>
        {% csrf_token %}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <template id="invoice_row">
        <tr>
            <td class="form-input-td" id="sl_no" disabled align="center">
            </td>
            <td class="form-input-td">
                <input type="text" id="code" autocomplete="off" list="code_options"
                       class="form-control product_search_area product_search_input" placeholder="Product Code">
            </td>
            <td class="form-input-td" colspan="4">
                <input type="text" id="name" autocomplete="off" list="name_options"
                       class="form-control product_search_area product_search_input" placeholder="Product">
            </td>
            <td class="form-input-td">
                <input type="text" id="quantity" class="form-control" placeholder="Quantity">
            </td>
            <td class="form-input-td">
                <input type="number" id="rate_wo_gst" step="any" class="form-control" >
            </td>
            <td class="form-input-td">
                <input type="number" id="s_gst" step="any" class="form-control" readonly>
            </td>
            <td class="form-input-td">
                <input type="number" id="amt" step="any" class="form-control" readonly>
            </td>
            <td hidden disabled>
                <input id="id">
            </td>
        </tr>
    </template>

    <datalist id="user_name_options">
    </datalist>
    <datalist id="user_phone_options">
    </datalist>
    <datalist id="code_options">
    </datalist>
    <datalist id="name_options">
    </datalist>

{% endblock %}



{% block includejs %}
    <script src="{% static "gstbillingapp/js/invoice_create/navigator.js" %}"></script>
    <script src="{% static "gstbillingapp/js/invoice_create/printer.js" %}"></script>
    <script src="{% static "gstbillingapp/js/invoice_create/main.js" %}"></script>
    <script src="{% static "gstbillingapp/js/invoice_create/customer.js" %}"></script>
{% endblock %}

billing/templates/gstbillingapp/login.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}
<div class="row">
<div class="col-sm">
</div>
<div class="col-sm">
	<div class="card" id="login-card">
		<h5 class="card-header">Login</h5>
		<div class="card-body">
			<h5 class="card-title">Login and start billing now!</h5>
			<!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
			<!--a href="{% url "social:begin" "google-oauth2" %}" class="btn btn-primary">Login with Google</a-->
		</div>
		<div>OR</div>
		<form method="POST">
			{% csrf_token %}
			<table class="table">
				<tbody class="two-col-form">
					<tr>
						<th scope="row" class="text-right">Username:</th>
						<td class="form-input-td">{{auth_form.username}}</td>
					</tr>`
					<tr>
						<th scope="row" class="text-right">Password:</th>
						<td class="form-input-td">{{auth_form.password}}</td>
					</tr>
				</tbody>
			</table>
		
			<input type="submit" class="btn btn-primary float-right" value="Submit">
		</form>

		
	</div>
		<a href="{% url 'signup_view' %}"><input class="btn btn-danger float-right" value="Sign Up"></a>
	</div>
<div class="col-sm">
</div>
</div>
{% endblock %}

billing/templates/gstbillingapp/product_edit.html
{% extends "gstbillingapp/base.html" %}

{% load static %}



{% block content %}

    <h2>Edit Product</h2>
    <form method="POST">
        {% csrf_token %}
        <table class="table">
            <tbody class="two-col-form">
            <tr>
                <th scope="row" class="text-right">Product Code:</th>
                <td class="form-input-td">{{ product_form.code }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-right">Product Name:</th>
                <td class="form-input-td">{{ product_form.title }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-right"><label for="id_product_hsn">HSN:</label></th>
                <td class="form-input-td">
                    <input type="text" name="product_hsn" id="id_product_hsn" list="hsn"
                           value="{% firstof product_form.get_hsn "" %}">
                </td>
            </tr>
            <tr>
                <th scope="row" class="text-right">GST Percent</th>
                <td class="form-input-td">{{ product_form.gst_percent }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-right">Price:</th>
                <td class="form-input-td">{{ product_form.price }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-right">Product stock:</th>
                <td class="form-input-td">{{ product_form.stock }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-right">price 2</th>
                <td class="form-input-td">{{ product_form.price2 }}</td>

            </tr>
            <tr>
                <th scope="row" class="text-right">price 3</th>
                <td class="form-input-td">{{ product_form.price3 }}</td>
            </tr>
            <tr>
                <th scope="row" class="text-right">Discount</th>
                <td class="form-input-td">{{ product_form.discount }}</td>
            </tr>
            </tbody>
        </table>

        <input type="submit" class="btn btn-primary float-right" value="Submit">
    </form>

    <datalist id="hsn"></datalist>

    <script>
        const gst = document.getElementById("id_gst_percent");
        const hsn = document.getElementById("id_product_hsn");
        const list = document.getElementById("hsn");

        const db = {};

        hsn.onkeyup = async ({target, key}) => {
            if (!key)
                return;

            const {results} = await fetch(`/bill/hsn?search=${target.value}`).then((res) => res.json());

            list.innerHTML = results.map(({code, gst_percent, id}) =>
                `<option data-id="${id}" data-gst="${gst_percent}" value="${code}">`)
                .join("");

            results.forEach(({code, gst_percent}) => db[code] = gst_percent);
        }

        hsn.onchange = (e) => gst.value = document.querySelector(`option[value="${e.target.value}"]`)
            ?.getAttribute("data-gst");

    </script>
{% endblock %}